[package]
name = "event-listener"
version = "2.5.1"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "Notify async tasks or threads"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/smol-rs/event-listener"
homepage = "https://github.com/smol-rs/event-listener"
documentation = "https://docs.rs/event-listener"
keywords = ["condvar", "eventcount", "wake", "blocking", "park"]
categories = ["asynchronous", "concurrency"]

[dependencies]
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[dev-dependencies]
futures = { version = "0.3.5", default-features = false, features = ["std"] }
waker-fn = "1.0.0"

[features]
phala-sgx = ["sgx_tstd"]